name = "DiffEqParamEstim"
uuid = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.27.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
PenaltyFunctions = "06bb1623-fdd5-5ca2-a01c-88eae3ea319e"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[compat]
Calculus = "0.5"
Dierckx = "0.4, 0.5"
DiffEqBase = "6"
Distributions = "0.25"
ForwardDiff = "0.10"
LsqFit = "0.8, 0.9, 0.10, 0.11, 0.12"
PenaltyFunctions = "0.1, 0.2, 0.3"
PreallocationTools = "0.2, 0.3, 0.4"
RecursiveArrayTools = "1.0, 2.0"
SciMLBase = "1"
SciMLSensitivity = "7"
julia = "1.6"

[extras]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BlackBoxOptim", "DelayDiffEq", "LeastSquaresOptim", "NLopt", "Optim", "OrdinaryDiffEq", "ParameterizedFunctions", "Random", "StochasticDiffEq", "SteadyStateDiffEq"]
