[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BlackBoxOptim = "0.6"
DiffEqParamEstim = "2"
DifferentialEquations = "7"
Distributions = "0.25"
Documenter = "1"
ForwardDiff = "0.10"
LeastSquaresOptim = "0.8"
NLopt = "0.6, 1"
Optim = "1"
Optimization = "3"
OptimizationBBO = "0.1, 0.2"
OptimizationMOI = "0.1, 0.2"
OptimizationNLopt = "0.1"
OptimizationOptimJL = "0.1"
Plots = "1"
RecursiveArrayTools = "2, 3"
SciMLSensitivity = "7"
Zygote = "0.6"
